
var Stockfish = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(Stockfish) {
  Stockfish = Stockfish || {};


function d(){k.buffer!=l&&n(k.buffer);return aa}function v(){k.buffer!=l&&n(k.buffer);return ba}function w(){k.buffer!=l&&n(k.buffer);return ca}function da(){k.buffer!=l&&n(k.buffer);return ea}null;var y;y||(y=typeof Stockfish !== 'undefined' ? Stockfish : {});var fa=Object.assign,ha,ja;y.ready=new Promise(function(a,b){ha=a;ja=b});
(function(){function a(){var g=e.shift();if(!b&&void 0!==g){if("quit"===g)return y.terminate();var m=y.ccall("uci_command","number",["string"],[g]);m&&e.unshift(g);h=m?2*h:1;setTimeout(a,h)}}var b=!1,c=[];y.print=function(g){0===c.length?console.log(g):setTimeout(function(){for(var m=0;m<c.length;m++)c[m](g)})};y.addMessageListener=function(g){c.push(g)};y.removeMessageListener=function(g){g=c.indexOf(g);0<=g&&c.splice(g,1)};y.terminate=function(){b=!0;z.pa()};var e=[],h=1;y.postMessage=function(g){e.push(g)};
y.postRun=function(){y.postMessage=function(g){e.push(g);1===e.length&&a()};a()}})();var ka=fa({},y),la=[],A="./this.program",B=(a,b)=>{throw b;},ma="object"===typeof window,C="function"===typeof importScripts,D="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,E=y.ENVIRONMENT_IS_PTHREAD||!1,F="";function na(a){return y.locateFile?y.locateFile(a,F):F+a}var H,I,fs,J,K;
if(D){F=C?require("path").dirname(F)+"/":__dirname+"/";K=function(){J||(fs=require("fs"),J=require("path"))};H=function(b,c){K();b=J.normalize(b);return fs.readFileSync(b,c?null:"utf8")};I=function(b){b=H(b,!0);b.buffer||(b=new Uint8Array(b));return b};1<process.argv.length&&(A=process.argv[1].replace(/\\/g,"/"));la=process.argv.slice(2);process.on("uncaughtException",function(b){if(!(b instanceof L))throw b;});process.on("unhandledRejection",function(b){throw b;});B=(b,c)=>{if(M())throw process.exitCode=
b,c;c instanceof L||N("exiting due to exception: "+c);process.exit(b)};y.inspect=function(){return"[Emscripten Module object]"};let a;try{a=require("worker_threads")}catch(b){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),b;}global.Worker=a.Worker}else if(ma||C)C?F=self.location.href:"undefined"!==typeof document&&document.currentScript&&(F=document.currentScript.src),_scriptDir&&(F=_scriptDir),0!==F.indexOf("blob:")?
F=F.substr(0,F.replace(/[?#].*/,"").lastIndexOf("/")+1):F="",D?(K=function(){J||(fs=require("fs"),J=require("path"))},H=function(a,b){K();a=J.normalize(a);return fs.readFileSync(a,b?null:"utf8")},I=function(a){a=H(a,!0);a.buffer||(a=new Uint8Array(a));return a}):(H=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},C&&(I=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));
D&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);var oa=console.log.bind(console),pa=console.warn.bind(console);D&&(K(),oa=a=>fs.writeSync(1,a+"\n"),pa=a=>fs.writeSync(2,a+"\n"));var qa=y.print||oa,N=y.printErr||pa;fa(y,ka);ka=null;y.arguments&&(la=y.arguments);y.thisProgram&&(A=y.thisProgram);y.quit&&(B=y.quit);var O,P;y.wasmBinary&&(P=y.wasmBinary);var noExitRuntime=y.noExitRuntime||!0;"object"!==typeof WebAssembly&&Q("no native wasm support detected");
var k,ra,sa=!1;function ta(a){var b=new TextDecoder(a);this.decode=c=>{c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var ua="undefined"!==typeof TextDecoder?new ta("utf8"):void 0;
function va(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&ua)return ua.decode(a.subarray(b,c));for(e="";b<c;){var h=a[b++];if(h&128){var g=a[b++]&63;if(192==(h&224))e+=String.fromCharCode((h&31)<<6|g);else{var m=a[b++]&63;h=224==(h&240)?(h&15)<<12|g<<6|m:(h&7)<<18|g<<12|m<<6|a[b++]&63;65536>h?e+=String.fromCharCode(h):(h-=65536,e+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else e+=String.fromCharCode(h)}return e}function R(a){return a?va(v(),a,void 0):""}
function T(a,b,c,e){if(0<e){e=c+e-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=e)break;b[c++]=g}else{if(2047>=g){if(c+1>=e)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=e)break;b[c++]=224|g>>12}else{if(c+3>=e)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}
function wa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new ta("utf-16le");function xa(a){var b=wa(a)+1,c=U(b);T(a,d(),c,b);return c}function ya(a,b){d().set(a,b)}var l,aa,ba,ca,ea;E&&(l=y.buffer);
function n(a){l=a;y.HEAP8=aa=new Int8Array(a);y.HEAP16=new Int16Array(a);y.HEAP32=ca=new Int32Array(a);y.HEAPU8=ba=new Uint8Array(a);y.HEAPU16=new Uint16Array(a);y.HEAPU32=new Uint32Array(a);y.HEAPF32=new Float32Array(a);y.HEAPF64=ea=new Float64Array(a)}var za=y.INITIAL_MEMORY||71303168;
if(E)k=y.wasmMemory,l=y.buffer;else if(y.wasmMemory)k=y.wasmMemory;else if(k=new WebAssembly.Memory({initial:za/65536,maximum:32768,shared:!0}),!(k.buffer instanceof SharedArrayBuffer))throw N("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),D&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");k&&(l=k.buffer);za=l.byteLength;n(l);var Aa,Ba=[],Ca=[],Da=[],Ea=[],Fa=0;function M(){return noExitRuntime||0<Fa}function Ga(){var a=y.preRun.shift();Ba.unshift(a)}var V=0,Ha=null,W=null;y.preloadedImages={};y.preloadedAudios={};function Q(a){if(E)postMessage({cmd:"onAbort",arg:a});else if(y.onAbort)y.onAbort(a);a="Aborted("+a+")";N(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");ja(a);throw a;}
function Ia(){return X.startsWith("data:application/octet-stream;base64,")}var X;X="stockfish.wasm";Ia()||(X=na(X));function Ja(){var a=X;try{if(a==X&&P)return new Uint8Array(P);if(I)return I(a);throw"both async and sync fetching of the wasm failed";}catch(b){Q(b)}}
function Ka(){return P||!ma&&!C||"function"!==typeof fetch?Promise.resolve().then(function(){return Ja()}):fetch(X,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+X+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}var La={};function Y(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(y);else{var c=b.Sa;"number"===typeof c?void 0===b.da?Ma(c)():Ma(c)(b.da):c(void 0===b.da?null:b.da)}}}
function Na(a){var b=Oa();a=a();Pa(b);return a}function Qa(a){var b=z.Z[a];b&&(w()[a>>2]=0,z.oa(b.worker))}function Ra(a){a instanceof L||"unwind"==a||B(1,a)}
var z={$:[],fa:[],ra:[],Ca:function(){for(var a=0;1>a;++a)z.sa()},Da:function(){z.receiveObjectTransfer=z.Fa;z.threadInit=z.xa;z.setExitStatus=z.Ha},Z:{},Ha:function(){},pa:function(){for(var a in z.Z){var b=z.Z[a];b&&b.worker&&z.oa(b.worker)}for(a=0;a<z.$.length;++a)z.$[a].terminate();z.$=[]},oa:function(a){z.Ga(function(){delete z.Z[a.aa.qa];z.$.push(a);z.fa.splice(z.fa.indexOf(a),1);Sa(a.aa.qa);a.aa=void 0})},Ga:function(a){w()[Ta>>2]=0;try{a()}finally{w()[Ta>>2]=1}},Fa:function(){},xa:function(){for(var a in z.ra)z.ra[a]()},
va:function(a,b){a.onmessage=function(c){c=c.data;var e=c.cmd;a.aa&&(z.ya=a.aa.qa);if(c.targetThread&&c.targetThread!=Ua()){var h=z.Z[c.Za];h?h.worker.postMessage(c,c.transferList):N('Internal error! Worker sent a message "'+e+'" to target pthread '+c.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Va();else if("spawnThread"===e)Wa(c);else if("cleanupThread"===e)Qa(c.thread);else if("killThread"===e)c=c.thread,w()[c>>2]=0,e=z.Z[c],delete z.Z[c],e.worker.terminate(),
Sa(c),z.fa.splice(z.fa.indexOf(e.worker),1),e.worker.aa=void 0;else if("cancelThread"===e)z.Z[c.thread].worker.postMessage({cmd:"cancel"});else if("loaded"===e)a.loaded=!0,b&&b(a),a.ea&&(a.ea(),delete a.ea);else if("print"===e)qa("Thread "+c.threadId+": "+c.text);else if("printErr"===e)N("Thread "+c.threadId+": "+c.text);else if("alert"===e)alert("Thread "+c.threadId+": "+c.text);else if("detachedExit"===e)z.oa(a);else if("setimmediate"===c.target)a.postMessage(c);else if("onAbort"===e){if(y.onAbort)y.onAbort(c.arg)}else N("worker sent an unknown command "+
e);z.ya=void 0};a.onerror=function(c){N("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};D&&(a.on("message",function(c){a.onmessage({data:c})}),a.on("error",function(c){a.onerror(c)}),a.on("detachedExit",function(){}));a.postMessage({cmd:"load",urlOrBlob:y.mainScriptUrlOrBlob||_scriptDir,wasmMemory:k,wasmModule:ra})},sa:function(){var a=na("stockfish.worker.js");z.$.push(new Worker(a))},Aa:function(){0==z.$.length&&(z.sa(),z.va(z.$[0]));return z.$.pop()}};
y.establishStackSpace=function(){var a=Ua(),b=w()[a+44>>2];a=w()[a+48>>2];Xa(b,b-a);Pa(b)};function Ya(a){if(E)return Z(1,0,a);try{Za(a)}catch(b){Ra(b)}}var $a=[];function Ma(a){var b=$a[a];b||(a>=$a.length&&($a.length=a+1),$a[a]=b=Aa.get(a));return b}y.invokeEntryPoint=function(a,b){return Ma(a)(b)};var ab;ab=D?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:E?()=>performance.now()-y.__performance_now_clock_drift:()=>performance.now();
function Wa(a){var b=z.Aa();if(!b)return 6;z.fa.push(b);var c=z.Z[a.na]={worker:b,qa:a.na};b.aa=c;var e={cmd:"run",start_routine:a.Ia,arg:a.da,threadInfoStruct:a.na};b.ea=function(){e.time=performance.now();b.postMessage(e,a.Na)};b.loaded&&(b.ea(),delete b.ea);return 0}var bb=[null,[],[]],cb={};function db(a,b,c){return E?Z(3,1,a,b,c):0}function eb(a,b,c){return E?Z(4,1,a,b,c):0}function fb(a,b,c){if(E)return Z(5,1,a,b,c)}
function Z(a,b){var c=arguments.length-2,e=arguments;return Na(function(){for(var h=U(8*c),g=h>>3,m=0;m<c;m++){var r=e[2+m];da()[g+m]=r}return gb(a,c,h,b)})}var hb=[];function ib(a,b,c,e){Na(function(){var h=U(12),g=0;if(b){g=wa(b)+1;var m=jb(g);T(b,v(),m,g);g=m}w()[h>>2]=g;w()[h+4>>2]=c;w()[h+8>>2]=e;kb(a,657457152,0,g,h)})}var lb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function mb(a){a=2<a?R(a):a;return lb[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function nb(a,b,c){var e=mb(a);if(!e)return-4;e.ja&&(w()[e.ja>>2]=b,w()[e.ja+4>>2]=c);if(e.wa||!e.Pa)e.wa&&(e=e.wa),a=!1,e.ia&&e.ia.ha&&(a=e.ia.ha.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===e.width&&a[3]===e.height),e.width=b,e.height=c,a&&e.ia.ha.viewport(0,0,b,c);else return e.ja?(e=w()[e.ja+8>>2],a=a?R(a):"",ib(e,a,b,c),1):-4;return 0}
function ob(a,b,c){return E?Z(6,1,a,b,c):nb(a,b,c)}function pb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,h,g){b.drawArraysInstancedANGLE(c,e,h,g)},a.drawElementsInstanced=function(c,e,h,g,m){b.drawElementsInstancedANGLE(c,e,h,g,m)})}
function qb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function rb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}
function sb(a,b){a.ua||(a.ua=a.getContext,a.getContext=function(e,h){h=a.ua(e,h);return"webgl"==e==h instanceof WebGLRenderingContext?h:null});var c=a.getContext("webgl",b);return c?tb(c,b):0}function tb(a,b){var c=jb(8);w()[c+4>>2]=Ua();var e={Ua:c,attributes:b,version:b.Ea,ha:a};a.canvas&&(a.canvas.ia=e);("undefined"===typeof b.ta||b.ta)&&ub(e);return c}
function ub(a){a||(a=vb);if(!a.Ba){a.Ba=!0;var b=a.ha;pb(b);qb(b);rb(b);b.Qa=b.getExtension("EXT_disjoint_timer_query");b.Wa=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var vb,wb=["default","low-power","high-performance"],xb={};
function zb(){if(!Ab){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:A||"./this.program"},b;for(b in xb)void 0===xb[b]?delete a[b]:a[b]=xb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ab=c}return Ab}var Ab;
function Bb(a,b){if(E)return Z(7,1,a,b);var c=0;zb().forEach(function(e,h){var g=b+c;h=w()[a+4*h>>2]=g;for(g=0;g<e.length;++g)d()[h++>>0]=e.charCodeAt(g);d()[h>>0]=0;c+=e.length+1});return 0}function Cb(a,b){if(E)return Z(8,1,a,b);var c=zb();w()[a>>2]=c.length;var e=0;c.forEach(function(h){e+=h.length+1});w()[b>>2]=e;return 0}function Db(a){return E?Z(9,1,a):0}function Eb(a,b,c,e){if(E)return Z(10,1,a,b,c,e);a=cb.Ta(a);b=cb.Ra(a,b,c);w()[e>>2]=b;return 0}
function Fb(a,b,c,e,h){if(E)return Z(11,1,a,b,c,e,h)}function Gb(a,b,c,e){if(E)return Z(12,1,a,b,c,e);for(var h=0,g=0;g<c;g++){var m=w()[b>>2],r=w()[b+4>>2];b+=8;for(var x=0;x<r;x++){var q=v()[m+x],t=bb[a];0===q||10===q?((1===a?qa:N)(va(t,0)),t.length=0):t.push(q)}h+=r}w()[e>>2]=h;return 0}function Hb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ib(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var Jb=[31,29,31,30,31,30,31,31,30,31,30,31],Kb=[31,28,31,30,31,30,31,31,30,31,30,31];
function Lb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(Hb(a.getFullYear())?Jb:Kb)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Mb(a,b,c,e){function h(f,p,u){for(f="number"===typeof f?f.toString():f||"";f.length<p;)f=u[0]+f;return f}function g(f,p){return h(f,p,"0")}function m(f,p){function u(yb){return 0>yb?-1:0<yb?1:0}var G;0===(G=u(f.getFullYear()-p.getFullYear()))&&0===(G=u(f.getMonth()-p.getMonth()))&&(G=u(f.getDate()-p.getDate()));return G}function r(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function x(f){f=Lb(new Date(f.Y+1900,0,1),f.ma);var p=new Date(f.getFullYear()+1,0,4),u=r(new Date(f.getFullYear(),0,4));p=r(p);return 0>=m(u,f)?0>=m(p,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var q=w()[e+40>>2];e={La:w()[e>>2],Ka:w()[e+4>>2],ka:w()[e+8>>2],ga:w()[e+12>>2],ba:w()[e+16>>2],Y:w()[e+20>>2],la:w()[e+24>>2],ma:w()[e+28>>2],$a:w()[e+
32>>2],Ja:w()[e+36>>2],Ma:q?R(q):""};c=R(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in q)c=c.replace(new RegExp(t,"g"),q[t]);var S="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ia="January February March April May June July August September October November December".split(" ");q={"%a":function(f){return S[f.la].substring(0,3)},"%A":function(f){return S[f.la]},"%b":function(f){return ia[f.ba].substring(0,3)},"%B":function(f){return ia[f.ba]},"%C":function(f){return g((f.Y+1900)/100|0,2)},"%d":function(f){return g(f.ga,2)},"%e":function(f){return h(f.ga,2," ")},"%g":function(f){return x(f).toString().substring(2)},"%G":function(f){return x(f)},"%H":function(f){return g(f.ka,
2)},"%I":function(f){f=f.ka;0==f?f=12:12<f&&(f-=12);return g(f,2)},"%j":function(f){return g(f.ga+Ib(Hb(f.Y+1900)?Jb:Kb,f.ba-1),3)},"%m":function(f){return g(f.ba+1,2)},"%M":function(f){return g(f.Ka,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.ka&&12>f.ka?"AM":"PM"},"%S":function(f){return g(f.La,2)},"%t":function(){return"\t"},"%u":function(f){return f.la||7},"%U":function(f){var p=new Date(f.Y+1900,0,1),u=0===p.getDay()?p:Lb(p,7-p.getDay());f=new Date(f.Y+1900,f.ba,f.ga);return 0>
m(u,f)?g(Math.ceil((31-u.getDate()+(Ib(Hb(f.getFullYear())?Jb:Kb,f.getMonth()-1)-31)+f.getDate())/7),2):0===m(u,p)?"01":"00"},"%V":function(f){var p=new Date(f.Y+1901,0,4),u=r(new Date(f.Y+1900,0,4));p=r(p);var G=Lb(new Date(f.Y+1900,0,1),f.ma);return 0>m(G,u)?"53":0>=m(p,G)?"01":g(Math.ceil((u.getFullYear()<f.Y+1900?f.ma+32-u.getDate():f.ma+1-u.getDate())/7),2)},"%w":function(f){return f.la},"%W":function(f){var p=new Date(f.Y,0,1),u=1===p.getDay()?p:Lb(p,0===p.getDay()?1:7-p.getDay()+1);f=new Date(f.Y+
1900,f.ba,f.ga);return 0>m(u,f)?g(Math.ceil((31-u.getDate()+(Ib(Hb(f.getFullYear())?Jb:Kb,f.getMonth()-1)-31)+f.getDate())/7),2):0===m(u,p)?"01":"00"},"%y":function(f){return(f.Y+1900).toString().substring(2)},"%Y":function(f){return f.Y+1900},"%z":function(f){f=f.Ja;var p=0<=f;f=Math.abs(f)/60;return(p?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Ma},"%%":function(){return"%"}};for(t in q)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),q[t](e)));t=Nb(c);if(t.length>
b)return 0;ya(t,a);return t.length-1}E||z.Ca();var Ob=[null,Ya,function(a,b){if(E)return Z(2,1,a,b)},db,eb,fb,ob,Bb,Cb,Db,Eb,Fb,Gb];function Nb(a){var b=Array(wa(a)+1);T(a,b,0,b.length);return b}
var Tb={k:function(a){Pb(a,!C,1,!ma);z.xa()},z:function(a){E?postMessage({cmd:"cleanupThread",thread:a}):Qa(a)},e:function(a,b,c,e){if("undefined"===typeof SharedArrayBuffer)return N("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var h=[];if(E&&0===h.length)return Qb(687865856,a,b,c,e);a={Ia:c,na:a,da:e,Na:h};return E?(a.Oa="spawnThread",postMessage(a,h),0):Wa(a)},B:function(){postMessage({cmd:"detachedExit"})},g:db,w:eb,x:fb,u:function(){return 2097152},
m:function(a,b,c){var e=performance.now();c=e+c;for(Atomics.exchange(w(),Rb>>2,a);;){e=performance.now();if(e>c)return Atomics.exchange(w(),Rb>>2,0),-73;e=Atomics.exchange(w(),Rb>>2,0);if(0==e)break;Va();if(Atomics.load(w(),a>>2)!=b)return-6;Atomics.exchange(w(),Rb>>2,a)}return 0},l:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(E)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=z.Z[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},
b:function(){Q("")},y:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=ab();else return w()[Sb()>>2]=28,-1;w()[b>>2]=a/1E3|0;w()[b+4>>2]=a%1E3*1E6|0;return 0},h:function(){D||C||(O||(O={}),O["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(O["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,N("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))},
c:ab,o:function(a,b,c){v().copyWithin(a,b,b+c)},C:function(a,b,c){hb.length=b;c>>=3;for(var e=0;e<b;e++)hb[e]=da()[c+e];return(0>a?La[-a-1]:Ob[a]).apply(null,hb)},p:function(a){var b=v().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(a,e);0<e%65536&&(e+=65536-e%65536);a:{try{k.grow(Math.min(2147483648,e)-l.byteLength+65535>>>16);n(k.buffer);var h=1;break a}catch(g){}h=void 0}if(h)return!0}return!1},i:function(a,b,c){return mb(a)?
nb(a,b,c):ob(a,b,c)},A:function(){throw"unwind";},j:function(a,b){b>>=2;var c=w()[b+6];b={alpha:!!w()[b],depth:!!w()[b+1],stencil:!!w()[b+2],antialias:!!w()[b+3],premultipliedAlpha:!!w()[b+4],preserveDrawingBuffer:!!w()[b+5],powerPreference:wb[c],failIfMajorPerformanceCaveat:!!w()[b+7],Ea:w()[b+8],Va:w()[b+9],ta:w()[b+10],za:w()[b+11],Xa:w()[b+12],Ya:w()[b+13]};a=mb(a);return!a||b.za?0:sb(a,b)},r:Bb,s:Cb,d:function(a){Za(a)},f:Db,v:Eb,n:Fb,t:Gb,a:k||y.wasmMemory,q:function(a,b,c,e){return Mb(a,b,
c,e)}};
(function(){function a(h,g){y.asm=h.exports;z.ra.push(y.asm.I);Aa=y.asm.X;Ca.unshift(y.asm.D);ra=g;if(!E){var m=z.$.length;z.$.forEach(function(r){z.va(r,function(){if(!--m&&(V--,y.monitorRunDependencies&&y.monitorRunDependencies(V),0==V&&(null!==Ha&&(clearInterval(Ha),Ha=null),W))){var x=W;W=null;x()}})})}}function b(h){a(h.instance,h.module)}function c(h){return Ka().then(function(g){return WebAssembly.instantiate(g,e)}).then(function(g){return g}).then(h,function(g){N("failed to asynchronously prepare wasm: "+g);
Q(g)})}var e={a:Tb};E||(V++,y.monitorRunDependencies&&y.monitorRunDependencies(V));if(y.instantiateWasm)try{return y.instantiateWasm(e,a)}catch(h){return N("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return P||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||"function"!==typeof fetch?c(b):fetch(X,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,e).then(b,function(g){N("wasm streaming compile failed: "+g);N("falling back to ArrayBuffer instantiation");
return c(b)})})})().catch(ja);return{}})();y.___wasm_call_ctors=function(){return(y.___wasm_call_ctors=y.asm.D).apply(null,arguments)};y._main=function(){return(y._main=y.asm.E).apply(null,arguments)};var jb=y._malloc=function(){return(jb=y._malloc=y.asm.F).apply(null,arguments)};y._free=function(){return(y._free=y.asm.G).apply(null,arguments)};y._uci_command=function(){return(y._uci_command=y.asm.H).apply(null,arguments)};
y._emscripten_tls_init=function(){return(y._emscripten_tls_init=y.asm.I).apply(null,arguments)};var Sb=y.___errno_location=function(){return(Sb=y.___errno_location=y.asm.J).apply(null,arguments)},Pb=y.__emscripten_thread_init=function(){return(Pb=y.__emscripten_thread_init=y.asm.K).apply(null,arguments)};y._emscripten_current_thread_process_queued_calls=function(){return(y._emscripten_current_thread_process_queued_calls=y.asm.L).apply(null,arguments)};
var Qb=y._emscripten_sync_run_in_main_thread_4=function(){return(Qb=y._emscripten_sync_run_in_main_thread_4=y.asm.M).apply(null,arguments)},Va=y._emscripten_main_thread_process_queued_calls=function(){return(Va=y._emscripten_main_thread_process_queued_calls=y.asm.N).apply(null,arguments)},gb=y._emscripten_run_in_main_runtime_thread_js=function(){return(gb=y._emscripten_run_in_main_runtime_thread_js=y.asm.O).apply(null,arguments)},kb=y._emscripten_dispatch_to_thread_=function(){return(kb=y._emscripten_dispatch_to_thread_=
y.asm.P).apply(null,arguments)},Sa=y.__emscripten_thread_free_data=function(){return(Sa=y.__emscripten_thread_free_data=y.asm.Q).apply(null,arguments)};y.__emscripten_thread_exit=function(){return(y.__emscripten_thread_exit=y.asm.R).apply(null,arguments)};
var Ua=y._pthread_self=function(){return(Ua=y._pthread_self=y.asm.S).apply(null,arguments)},Xa=y._emscripten_stack_set_limits=function(){return(Xa=y._emscripten_stack_set_limits=y.asm.T).apply(null,arguments)},Oa=y.stackSave=function(){return(Oa=y.stackSave=y.asm.U).apply(null,arguments)},Pa=y.stackRestore=function(){return(Pa=y.stackRestore=y.asm.V).apply(null,arguments)},U=y.stackAlloc=function(){return(U=y.stackAlloc=y.asm.W).apply(null,arguments)},Rb=y.__emscripten_main_thread_futex=1097996,Ta=
y.__emscripten_allow_main_runtime_queued_calls=35036;y.ccall=function(a,b,c,e){var h={string:function(q){var t=0;if(null!==q&&void 0!==q&&0!==q){var S=(q.length<<2)+1,ia=t=U(S);T(q,v(),ia,S)}return t},array:function(q){var t=U(q.length);ya(q,t);return t}};a=y["_"+a];var g=[],m=0;if(e)for(var r=0;r<e.length;r++){var x=h[c[r]];x?(0===m&&(m=Oa()),g[r]=x(e[r])):g[r]=e[r]}c=a.apply(null,g);return c=function(q){0!==m&&Pa(m);return"string"===b?R(q):"boolean"===b?!!q:q}(c)};y.keepRuntimeAlive=M;
y.PThread=z;y.PThread=z;y.wasmMemory=k;y.ExitStatus=L;var Ub;function L(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}W=function Vb(){Ub||Wb();Ub||(W=Vb)};
function Wb(a){function b(){if(!Ub&&(Ub=!0,y.calledRun=!0,!sa)){E||Y(Ca);E||Y(Da);ha(y);if(y.onRuntimeInitialized)y.onRuntimeInitialized();if(Xb){var c=a,e=y._main;c=c||[];var h=c.length+1,g=U(4*(h+1));w()[g>>2]=xa(A);for(var m=1;m<h;m++)w()[(g>>2)+m]=xa(c[m-1]);w()[(g>>2)+h]=0;try{var r=e(h,g);Za(r,!0)}catch(x){Ra(x)}finally{}}if(!E){if(y.postRun)for("function"==typeof y.postRun&&(y.postRun=[y.postRun]);y.postRun.length;)c=y.postRun.shift(),Ea.unshift(c);Y(Ea)}}}a=a||la;if(!(0<V))if(E)ha(y),E||Y(Ca),
postMessage({cmd:"loaded"});else{if(y.preRun)for("function"==typeof y.preRun&&(y.preRun=[y.preRun]);y.preRun.length;)Ga();Y(Ba);0<V||(y.setStatus?(y.setStatus("Running..."),setTimeout(function(){setTimeout(function(){y.setStatus("")},1);b()},1)):b())}}y.run=Wb;function Za(a,b){if(!b&&E)throw Ya(a),"unwind";M()||E||z.pa();if(!M()){z.pa();if(y.onExit)y.onExit(a);sa=!0}B(a,new L(a))}if(y.preInit)for("function"==typeof y.preInit&&(y.preInit=[y.preInit]);0<y.preInit.length;)y.preInit.pop()();var Xb=!0;
y.noInitialRun&&(Xb=!1);E&&(noExitRuntime=!1,z.Da());Wb();


  return Stockfish.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Stockfish;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Stockfish; });
else if (typeof exports === 'object')
  exports["Stockfish"] = Stockfish;
